/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.9.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.api;

import org.openapitools.model.Recomendacion;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import javax.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2024-11-11T16:32:34.104885200+01:00[Europe/Madrid]", comments = "Generator version: 7.9.0")
@Validated
@Tag(name = "Recommendation", description = "Este endpoint maneja las diferentes operaciones sobre las recomendaciones")
public interface RecommendationsApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * GET /recommendations/film/{userID} : Obtener recomendaciones personalizadas
     * Retorna recomendaciones de peliculas basadas en las visualizaciones del usuario autenticado.
     *
     * @param userID ID del usuario. (required)
     * @return Recomendaciones recuperadas exitosamente (status code 200)
     *         or Usuario no autenticado (status code 401)
     *         or Error en el servidor (status code 500)
     */
    @Operation(
        operationId = "recommendationsFilmUserIDGet",
        summary = "Obtener recomendaciones personalizadas",
        description = "Retorna recomendaciones de peliculas basadas en las visualizaciones del usuario autenticado.",
        tags = { "Recommendation" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Recomendaciones recuperadas exitosamente", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = Recomendacion.class)))
            }),
            @ApiResponse(responseCode = "401", description = "Usuario no autenticado"),
            @ApiResponse(responseCode = "500", description = "Error en el servidor")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/recommendations/film/{userID}",
        produces = { "application/json" }
    )
    
    default ResponseEntity<List<Recomendacion>> recommendationsFilmUserIDGet(
        @Parameter(name = "userID", description = "ID del usuario.", required = true, in = ParameterIn.PATH) @PathVariable("userID") Integer userID
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "[ { \"photoURL\" : \"https://example.com/photo.jpg\", \"filmID\" : 1, \"serieID\" : 1, \"title\" : \"El Señor de los Anillos\" }, { \"photoURL\" : \"https://example.com/photo.jpg\", \"filmID\" : 1, \"serieID\" : 1, \"title\" : \"El Señor de los Anillos\" } ]";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /recommendations/serie/{userID} : Obtener recomendaciones personalizadas
     * Retorna recomendaciones de series basadas en las visualizaciones del usuario autenticado.
     *
     * @param userID ID del usuario. (required)
     * @return Recomendaciones recuperadas exitosamente (status code 200)
     *         or Usuario no autenticado (status code 401)
     *         or Error en el servidor (status code 500)
     */
    @Operation(
        operationId = "recommendationsSerieUserIDGet",
        summary = "Obtener recomendaciones personalizadas",
        description = "Retorna recomendaciones de series basadas en las visualizaciones del usuario autenticado.",
        tags = { "Recommendation" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Recomendaciones recuperadas exitosamente", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = Recomendacion.class)))
            }),
            @ApiResponse(responseCode = "401", description = "Usuario no autenticado"),
            @ApiResponse(responseCode = "500", description = "Error en el servidor")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/recommendations/serie/{userID}",
        produces = { "application/json" }
    )
    
    default ResponseEntity<List<Recomendacion>> recommendationsSerieUserIDGet(
        @Parameter(name = "userID", description = "ID del usuario.", required = true, in = ParameterIn.PATH) @PathVariable("userID") Integer userID
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "[ { \"photoURL\" : \"https://example.com/photo.jpg\", \"filmID\" : 1, \"serieID\" : 1, \"title\" : \"El Señor de los Anillos\" }, { \"photoURL\" : \"https://example.com/photo.jpg\", \"filmID\" : 1, \"serieID\" : 1, \"title\" : \"El Señor de los Anillos\" } ]";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
